<a href="https://colab.research.google.com/github/Aminsch/test/blob/main/Untitled5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import sklearn

In [2]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer
from sklearn.preprocessing import RobustScaler
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.compose import make_column_selector as selector
from sklearn.pipeline import Pipeline

In [5]:
train_data = pd.read_csv('../ames.csv',nrows=2000)
test_data = pd.read_csv('../ames.csv', skiprows=2000)
train_data

,MS_SubClass,MS_Zoning,Lot_Frontage,Lot_Area,Street,Alley,Lot_Shape,Land_Contour,Utilities,Lot_Config,...,Fence,Misc_Feature,Misc_Val,Mo_Sold,Year_Sold,Sale_Type,Sale_Condition,Sale_Price,Longitude,Latitude
0,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,141,31770,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,Corner,...,No_Fence,None,0,5,2010,WD,Normal,215000,-93.619754,42.054035
1,One_Story_1946_and_Newer_All_Styles,Residential_High_Density,80,11622,Pave,No_Alley_Access,Regular,Lvl,AllPub,Inside,...,Minimum_Privacy,None,0,6,2010,WD,Normal,105000,-93.619756,42.053014
2,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,81,14267,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,Corner,...,No_Fence,Gar2,12500,6,2010,WD,Normal,172000,-93.619387,42.052659
3,One_Story_1946_and_Newer_All_Styles,Residential_Low_Density,93,11160,Pave,No_Alley_Access,Regular,Lvl,AllPub,Corner,...,No_Fence,None,0,4,2010,WD,Normal,244000,-93.617320,42.051245
4,Two_Story_1946_and_Newer,Residential_Low_Density,74,13830,Pave,No_Alley_Access,Slightly_Irregular,Lvl,AllPub,Inside,...,Minimum_Privacy,None,0,3,2010,WD,Normal,189900,-93.638933,42.060899
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,Two_Story_1945_and_Older,Residential_Medium_Density,90,9900,Pave,No_Alley_Access,Regular,Lvl,AllPub,Inside,...,No_Fence,None,0,5,2007,WD,Normal,117500,-93.617037,42.028076
1996,Two_Story_1945_and_Older,Residential_Medium_Density,60,3600,Pave,Gravel,Regular,Lvl,AllPub,Inside,...,Minimum_Privacy,None,0,7,2007,WD,Partial,124500,-93.615578,42.028847
1997,Two_and_Half_Story_All_Ages,Residential_Medium_Density,75,13500,Pave,Gravel,Regular,Lvl,AllPub,Corner,...,Minimum_Privacy,None,0,2,2007,WD,Normal,185000,-93.612061,42.028190
1998,Two_Family_conversion_All_Styles_and_Ages,C_all,60,7200,Pave,No_Alley_Access,Regular,Lvl,AllPub,Corner,...,No_Fence,None,0,11,2007,WD,Normal,133900,-93.612191,42.027154
1999,One_Story_with_Finished_Attic_All_Ages,Residential_Medium_Density,40,5400,Pave,Paved,Regular,Lvl,AllPub,Corner,...,No_Fence,None,0,10,2007,WD,Normal,152000,-93.608882,42.028200

In [6]:
print(train_data.apply(lambda col: col.dtypes))

MS_SubClass        object
MS_Zoning          object
Lot_Frontage        int64
Lot_Area            int64
Street             object
                   ...
Sale_Type          object
Sale_Condition     object
Sale_Price          int64
Longitude         float64
Latitude          float64
Length: 81, dtype: object

In [33]:
categorical_list = list(test_data.select_dtypes(include='object'))

train_data['train'] =1
test_data['train'] =0
combined = pd.concat([train_data, test_data])

for col in categorical_list:
    combined[col] = combined[col].astype('category').cat.codes

train_data = combined[combined['train']==1]
test_data = combined[combined['train']==0]
train_data = train_data.drop(['train'] ,axis=1)
test_data = test_data.drop(['train','Sale_Price'], axis=1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.

In [34]:
numeric_transformer = Pipeline(steps=[
    ('imputer', IterativeImputer(random_state=42)), 
    ('scaler', RobustScaler())
])

categorical_transformer = Pipeline(steps=[
    ('imputer', IterativeImputer(random_state=42))
])

In [35]:
preprocessor = ColumnTransformer(transformers=[
    ('num', numeric_transformer, selector(dtype_exclude='object')),
    ('cat', categorical_transformer, selector(dtype_include='object'))
])

In [36]:
from sklearn.linear_model import Lasso
from sklearn.metrics import mean_absolute_error

lasso = Lasso(alpha=0.0008)

lasso_pipeline = Pipeline(steps=[
    ('preprocess', preprocessor),
    ('model', lasso)
])

In [37]:
y_train = train_data['Sale_Price']
x_train = train_data.drop('Sale_Price', axis=1)

In [38]:
x_train, x_valid, y_train, y_valid = train_test_split(x_train, y_train, test_size=0.2, random_state=42)

In [39]:
lasso_pipeline.fit(x_train, y_train)

/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_coordinate_descent.py:648: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 5.868e+11, tolerance: 9.843e+08
  coef_, l1_reg, l2_reg, X, y, max_iter, tol, rng, random, positive

Pipeline(steps=[('preprocess',
                 ColumnTransformer(transformers=[('num',
                                                  Pipeline(steps=[('imputer',
                                                                   IterativeImputer(random_state=42)),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x7f8ff9d1c790>),
                                                 ('cat',
                                                  Pipeline(steps=[('imputer',
                                                                   IterativeImputer(random_state=42))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x7f8ff9d1c190>)])),
                ('model', Lasso(alpha=0.0008))])

In [44]:
y_pred = lasso_pipeline.predict(x_valid)
print("MSE ", np.sqrt(mean_squared_error(y_valid, y_pred)))

MSE  35986.56926341183

In [45]:
predicition = lasso_pipeline.predict(test_data)

In [46]:
output = pd.DataFrame({'Sales_Price' : predicition})
output

       Sales_Price
0    346373.001792
1    346373.001792
2    346373.001792
3    346373.001792
4    346373.001792
..             ...
925  346373.001792
926  346373.001792
927  346373.001792
928  346373.001792
929  346373.001792

[930 rows x 1 columns]